- name: install apache2
  yum:
    name: httpd
    state: latest
- service:
    name: httpd
    state: started
    enabled: yes
- name: copy index.html file
  copy:
    src: ~/roles/apache_ins/files/index.html
    dest: /var/www/html

